spring:
 application:
  name: icu-reactive-service

 r2dbc:
  url: r2dbc:postgresql://localhost:5432/icu_reactive_db 
  username: postgres
  password: postgres  
  
 liquibase:
  enabled: false
  url: jdbc:postgresql://localhost:5432/icu_reactive_db
  user: postgres
  password: postgres

 config:
  import: configserver:http://localhost:8888

 cloud:
  function:
   definition: save
  stream:
   bindings:
    save-in-0:
     destination: transfer-out

# eureka:
#  client: 
#   service-url:
#    default-zone: http://localhost:8761/eureka
#   fetch-registry: true
#   register-with-eureka: true

server:
 port: 8082